"""
Report Distributor — Slack + Gmail
====================================
Sends rendered report via Slack and/or Gmail.
"""

import os
import json
import logging
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.application import MIMEApplication
from pathlib import Path
from typing import Optional

import httpx

logger = logging.getLogger("distributor")


async def distribute_report(
    report_id: str,
    report_paths: dict,
    recipients: list[str],
    slack_channel: Optional[str],
    send_email: bool,
    send_slack: bool,
    company_id: str,
    period: str,
) -> dict:
    """
    Distribute report via Slack and/or Gmail.

    Returns:
        dict with distribution results
    """
    results = {}

    if send_slack and slack_channel:
        results["slack"] = await send_slack_notification(
            channel=slack_channel,
            report_id=report_id,
            company_id=company_id,
            period=period,
            report_paths=report_paths,
        )

    if send_email and recipients:
        results["email"] = await send_email_report(
            recipients=recipients,
            report_id=report_id,
            company_id=company_id,
            period=period,
            report_paths=report_paths,
        )

    return results


async def send_slack_notification(
    channel: str,
    report_id: str,
    company_id: str,
    period: str,
    report_paths: dict,
) -> dict:
    """Send Slack notification with report summary."""

    slack_token = os.getenv("SLACK_BOT_TOKEN")
    if not slack_token:
        logger.warning("SLACK_BOT_TOKEN not set — skipping Slack notification")
        return {"status": "skipped", "reason": "SLACK_BOT_TOKEN not configured"}

    message = {
        "channel": channel,
        "blocks": [
            {
                "type": "header",
                "text": {
                    "type": "plain_text",
                    "text": f"📊 Executive Report Ready — {company_id} | {period}",
                },
            },
            {
                "type": "section",
                "fields": [
                    {"type": "mrkdwn", "text": f"*Report ID:*\n`{report_id}`"},
                    {"type": "mrkdwn", "text": f"*Period:*\n{period}"},
                    {"type": "mrkdwn", "text": f"*Company:*\n{company_id}"},
                    {
                        "type": "mrkdwn",
                        "text": f"*Formats:*\n{'PDF ✅' if report_paths.get('pdf') else 'PDF ❌'} | {'HTML ✅' if report_paths.get('html') else 'HTML ❌'}",
                    },
                ],
            },
            {
                "type": "context",
                "elements": [
                    {
                        "type": "mrkdwn",
                        "text": "Generated by n8n Executive Reporting Pipeline · Powered by Claude API",
                    }
                ],
            },
        ],
    }

    try:
        async with httpx.AsyncClient() as client:
            response = await client.post(
                "https://slack.com/api/chat.postMessage",
                headers={"Authorization": f"Bearer {slack_token}"},
                json=message,
                timeout=10,
            )
            data = response.json()
            if data.get("ok"):
                logger.info(f"Slack notification sent to {channel}")
                return {"status": "sent", "channel": channel, "ts": data.get("ts")}
            else:
                return {"status": "failed", "error": data.get("error")}

    except Exception as e:
        logger.error(f"Slack error: {e}")
        return {"status": "error", "error": str(e)}


async def send_email_report(
    recipients: list[str],
    report_id: str,
    company_id: str,
    period: str,
    report_paths: dict,
) -> dict:
    """Send email with PDF report attached via Gmail SMTP."""

    smtp_user = os.getenv("GMAIL_USER")
    smtp_pass = os.getenv("GMAIL_APP_PASSWORD")

    if not smtp_user or not smtp_pass:
        logger.warning("Gmail credentials not set — skipping email")
        return {"status": "skipped", "reason": "Gmail credentials not configured"}

    msg = MIMEMultipart()
    msg["From"] = smtp_user
    msg["To"] = ", ".join(recipients)
    msg["Subject"] = f"Executive Report — {company_id} | {period}"

    body = f"""
    <html><body>
    <h2>Executive Report — {company_id}</h2>
    <p><strong>Period:</strong> {period}</p>
    <p><strong>Report ID:</strong> <code>{report_id}</code></p>
    <p>Please find the executive report attached.</p>
    <hr>
    <small>Generated automatically by n8n Executive Reporting Pipeline · Powered by Claude API</small>
    </body></html>
    """
    msg.attach(MIMEText(body, "html"))

    # Attach PDF if available
    pdf_path = report_paths.get("pdf")
    if pdf_path and Path(pdf_path).exists():
        with open(pdf_path, "rb") as f:
            attachment = MIMEApplication(f.read(), _subtype="pdf")
            attachment.add_header(
                "Content-Disposition",
                "attachment",
                filename=f"report_{company_id}_{period}.pdf",
            )
            msg.attach(attachment)

    try:
        with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
            server.login(smtp_user, smtp_pass)
            server.sendmail(smtp_user, recipients, msg.as_string())

        logger.info(f"Email sent to {recipients}")
        return {"status": "sent", "recipients": recipients}

    except Exception as e:
        logger.error(f"Email error: {e}")
        return {"status": "error", "error": str(e)}
